coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: components-to-markdown
      paths:
        - packages/components-to-markdown
      statuses:
        - type: project
          target: auto
          threshold: 40%
