version: 2.1

orbs:
  nx: nrwl/nx@1.5.1

jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      environment:
      MAIN_BRANCH_NAME: main
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: main
          workflow-name: nx-pipeline
      - run:
          name: Workspace Lint
          command: yarn nx workspace-lint
      - run:
          name: Format Check
          command: yarn nx format:check
      - run:
          name: Run Lint
          command: yarn nx affected --target=lint --base=$NX_BASE
      - run:
          name: Run Unit Tests
          command: yarn nx affected --target=test --base=$NX_BASE
      - run:
          name: Run Builds
          command: yarn nx affected --target=build --base=$NX_BASE

workflows:
  build:
    jobs:
      - main
