name: Bug Report 🪲
description: Create a bug report to help us improve
title: '[Bug]: '
labels: ['bug', 'needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Expected Behavior
        <!--- Tell us what should happen. -->
  - type: markdown
    attributes:
      value: |
        ## Current Behavior
        <!--- Tell us what happens instead of the expected behavior. -->
  - type: markdown
    attributes:
      value: |
        ## Steps to Reproduce
        <!--- Provide an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant. -->
        1.
        2.
        3.
  - type: markdown
    attributes:
      value: |
        ## Possible Solution
        <!--- Not obligatory, but suggest a fix/reason for the bug. -->
  - type: markdown
    attributes:
      value: |
        ## Context (Environment)
        <!--- Providing context helps us come up with a solution that is most useful in the real world.  -->
