---
name: Documentation 📚
about: Report an issue or suggest an improvement related to documentation.
title: '[Docs]: '
labels: documentation, needs triage
---

This template is strictly used for documentation requests, including:

- Documenting undocumented APIs;
- Elaborating on a particular topic;
- Updating external links;
- anything else that doesn't require touching the codebase itself.

If you followed the documentation but things don't work, take some time to consider if it's the documentation or the code that's wrong. In the latter, prefer using the "bug" template.

You may proceed directly to sending a pull request without filing this issue, and we can improve on your work.
